apiVersion: v1
kind: Pod
metadata:
  name: bad-worker
  namespace: default
  labels:
    app: demo
spec:
  hostNetwork: true
  containers:
    - name: app
      image: nginx:latest
      securityContext:
        privileged: true
      resources:
        requests:
          cpu: 50m
          memory: 64Mi
