apiVersion: v1
kind: Pod
metadata:
  name: good-worker
  namespace: default
  labels:
    app: demo
    team: platform
spec:
  containers:
    - name: app
      image: registry.k8s.io/pause:3.9
      resources:
        limits:
          cpu: 100m
          memory: 128Mi
        requests:
          cpu: 50m
          memory: 64Mi
